# Generated by Django 4.2.7 on 2023-11-05 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shops',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
